### PR TITLE
fromStream Updates

### PR DESCRIPTION
**Pull request by mrvwman**
* Fixed fromStream by adding frameCount
* Added connectDestination option
* Added test page

### CODE REVIEW

**Comment by probabble** [comment]
these changes were helpful for me and my little voice recording interface

**Review by foobar404 — APPROVED** [review]

**Review by foobar404 — APPROVED** [review]

**Comment by Avadakedvr** [comment]
Hey - this does not work for me for some reason. I've tried from element, that works. From stream, no luck..

**Comment by robinmanuelthiel** [comment]
It does not work, because although these changes are merged, no new version containing them has been released to NPM...

**Comment by korbav** [comment]
> 
> 
> It does not work, because although these changes are merged, no new version containing them has been released to NPM...

I got you, unfortunately, the author of the project seems to be have been away for quite a while, I'm even sure if there will be any change in the future. I would advise you, for the moment, to add your npm dependency on the master branch : 

`npm install git://github.com/foobar404/Wave.js.git#master --save`

**Pull request merged**
